package main

import (
	"bytes"
	_ "embed"
	"flag"
	"io/ioutil"
	"log"
	"strings"

	"github.com/valyala/fasttemplate"
)

var (
	dockerName string
	codeRoot   string
)

func init() {
	const (
		dockerUsage = "Docker image name (required)"
		rootUsage   = "Path to code root on disk (required)"
	)

	flag.StringVar(&dockerName, "n", "", dockerUsage)
	flag.StringVar(&codeRoot, "r", "", rootUsage)
	flag.Parse()

	// TODO: allow running in code root folder without flags
	// Exit with error if required flags are empty
	if dockerName == "" || rootUsage == "" {
		log.Fatalln("Missing -n (docker name) and/or -r (code root)")
	}

	// Trim space from name
	dockerName = strings.TrimSpace(dockerName)
}

//go:embed Makefile
var makeFile string

func main() {
	wGT := fasttemplate.New(makeFile, "{{", "}}")

	var b bytes.Buffer

	b.WriteString("# Auto generated by github.com/jdinabox/alpine-dockerfiles\n\n")
	b.WriteString(wGT.ExecuteString(map[string]interface{}{
		"docker-name": dockerName,
	}))

	ioutil.WriteFile(codeRoot+"/Makefile", b.Bytes(), 0644)
}
